refactor: update supported frameworks
TestableIO/System.IO.Abstractions pull request #1060
Opened 2023-12-04 08:48 UTC by vbreuss

Update frameworks in preparation to support [nunit v4](https://docs.nunit.org/articles/nunit/release-notes/framework.html#nunit-400---november-26-2023):
- Update .NET Framework 4.6.1 to .NET Framework 4.6.2
- Remove no longer supported version .NET 5
- Remove .NET Core 3.1 from test project

*For reference see #1058*

2023-12-04 11:07 UTC, fgreinacher requested changes
Very nice, thanks @vbreuss.

Just two minor things I noticed

2023-12-04 12:10 UTC, vbreuss commented on src/System.IO.Abstractions.TestingHelpers/System.IO.Abstractions.TestingHelpers.csproj
> +      <TargetFrameworks>net7.0;net6.0;netstandard2.1;netstandard2.0;net462</TargetFrameworks>
I am not sure, why this is displayed this way in GitHub 😕 

In [my branch](https://github.com/vbreuss/System.IO.Abstractions/blob/topic/update-framework-to-462/src/TestableIO.System.IO.Abstractions.TestingHelpers/TestableIO.System.IO.Abstractions.TestingHelpers.csproj) `net8.0` is present and it was [added](https://github.com/TestableIO/System.IO.Abstractions/pull/1032/files#diff-239e928c487ec3a47368cb73c027b87a980da1b5d8d2c23cd090f974a1c64347) in #1032.

Do you have any idea what happened, @fgreinacher?

2023-12-05 21:48 UTC, fgreinacher commented
I bump the version to 20.0 and added the breaking change trailer to the description.

2023-12-05 21:58 UTC, fgreinacher approved these changes
Thanks a ton @vbreuss 🙇

2023-12-05 21:58 UTC, merged